default: &default
  adapter: postgresql
  encoding: unicode
  username: wormer
  password: wormer-
  host: <%= ENV["DATABASE_HOST"] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #adapter: sqlite3

development:
  <<: *default
  database: deneme
  #database: db/deneme.db
test:
  <<: *default
  database: Api_Test_test

production:
  <<: *default
  database: Api_Test_production
  username: Api_Test
  password: <%= ENV["API_TEST_DATABASE_PASSWORD"] %>
